# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - vaccinenotifier1(Production), Build and deploy Spring app

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn clean install
      env:
        client: ${{secrets.CLIENT}}
        key: ${{secrets.KEY}}
        Keyvault: ${{secrets.KEYVAULT}}
        tenant: ${{secrets.TENANT}}

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: vaccinenotifier1
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4E4F15148B804BA3ACEFE43E394D1A4B }}
        package: ${{ github.workspace }}/target/*.jar

